Update TableLayoutSettings.xml
dotnet/dotnet-api-docs pull request #4813
Opened 2020-09-07 04:22 UTC by RussKie

## Summary

Improve docs.
Related to https://github.com/dotnet/winforms/issues/3578

2020-09-07 04:40 UTC, opbld32 commented
Docs Build status updates of commit _[e95120b](https://github.com/dotnet/dotnet-api-docs/commits/e95120b0f0509664a54bfbe20c5a9e7b2845b211)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Windows.Forms/TableLayoutSettings.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-1/xml/System.Windows.Forms/TableLayoutSettings.xml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tablelayoutsettings?view=net-5.0&branch=pr-en-us-4813) | [Details](#user-content-dcb549c4-33f30957)

<a id="dcb549c4-33f30957"></a>
### [xml/System.Windows.Forms/TableLayoutSettings.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-1/xml/System.Windows.Forms/TableLayoutSettings.xml)
 - **Line 0, Column 0**: **[Warning-xref-not-found]** `````Cross reference not found: 'int.MaxValue*'.`````
 - **Line 0, Column 0**: **[Warning-xref-not-found]** `````Cross reference not found: 'int.MaxValue*'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C7%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C202009070422554893-4813%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LicRWI2H9Vm%2Fo%2BbddrizpRHbgfY9zBLhpVukMREYyqk%3D&st=2020-09-07T04%3A35%3A40Z&se=2020-10-08T04%3A40%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-07 07:09 UTC, opbld34 commented
Docs Build status updates of commit _[78da22f](https://github.com/dotnet/dotnet-api-docs/commits/78da22f41c432984ed4e0f64bddef8dcdba56d8b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Windows.Forms/TableLayoutSettings.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-1/xml/System.Windows.Forms/TableLayoutSettings.xml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tablelayoutsettings?view=net-5.0&branch=pr-en-us-4813) | [Details](#user-content-dcb549c4-2dac524f)

<a id="dcb549c4-2dac524f"></a>
### [xml/System.Windows.Forms/TableLayoutSettings.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-1/xml/System.Windows.Forms/TableLayoutSettings.xml)
 - **Line 0, Column 0**: **[Warning-xref-not-found]** `````Cross reference not found: 'Int32.MaxValue*'.`````
 - **Line 0, Column 0**: **[Warning-xref-not-found]** `````Cross reference not found: 'Int32.MaxValue*'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C7%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C202009070650279353-4813%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=R2lhrj9YpFgB9Hn7oR95Why9Y21fBs%2FnlOJMhCAYUHw%3D&st=2020-09-07T07%3A04%3A47Z&se=2020-10-08T07%3A09%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-09 18:50 UTC, carlossanlop commented
@merriemcgaw @JuditRose can you please review?

2020-09-09 18:53 UTC, merriemcgaw approved these changes

2020-09-09 19:46 UTC, gewarren approved these changes

2020-09-09 19:48 UTC, gewarren requested changes

2020-09-09 19:48 UTC, gewarren commented on xml/System.Windows.Forms/TableLayoutSettings.xml
> + Setting the <xref:System.Windows.Forms.TableLayoutSettings.ColumnCount%2A> property does not create columns or allocate any backing memory. This allocation occurs when the columns are created, thus
```suggestion
 Setting the <xref:System.Windows.Forms.TableLayoutSettings.ColumnCount%2A> property does not create columns or allocate any backing memory. Memory allocation occurs when the columns are created, so you can set this property to <xref:System.Int32.MaxValue>.
```

2020-09-09 19:48 UTC, gewarren commented on xml/System.Windows.Forms/TableLayoutSettings.xml
> + Setting the <xref:System.Windows.Forms.TableLayoutSettings.RowCount%2A> property does not create rows or allocate any backing memory. This allocation occurs when the rows are created, thus this prop
```suggestion
 Setting the <xref:System.Windows.Forms.TableLayoutSettings.RowCount%2A> property does not create rows or allocate any backing memory. Memory allocation occurs when the rows are created, so you can set this property to <xref:System.Int32.MaxValue>.
```

2020-09-11 18:01 UTC, opbld30 commented
Docs Build status updates of commit _[01d7f23](https://github.com/dotnet/dotnet-api-docs/commits/01d7f235995c92e89e7ce9874c3b8d2edd9d6ab5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Windows.Forms/TableLayoutSettings.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-1/xml/System.Windows.Forms/TableLayoutSettings.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tablelayoutsettings?view=net-5.0&branch=pr-en-us-4813) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C11%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C202009111742073386-4813%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B%2FSR72e%2F98Oi6LwHtHLBgO0Aqi8YgP%2F3G3VMVXF2Los%3D&st=2020-09-11T17%3A56%3A44Z&se=2020-10-12T18%3A01%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-11 22:22 UTC, carlossanlop approved these changes

2020-09-11 22:24 UTC, gewarren approved these changes

2020-09-11 22:25 UTC, merged