Update TableLayoutPanel.xml
dotnet/dotnet-api-docs pull request #4814
Opened 2020-09-07 04:56 UTC by RussKie

## Summary

Improve docs.
Related to dotnet/winforms#3578

2020-09-07 04:58 UTC, opbld33 commented
Docs Build status updates of commit _[87ea07f](https://github.com/dotnet/dotnet-api-docs/commits/87ea07f5f0901605e03338176b10ddc5a03fa56b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Windows.Forms/TableLayoutPanel.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-2/xml/System.Windows.Forms/TableLayoutPanel.xml) | :x:Error | | [Details](#user-content-56b81b83-738cbe89)
[]() | :x:Error | | [Details](#user-content-738cbe89)

<a id="56b81b83-738cbe89"></a>
### [xml/System.Windows.Forms/TableLayoutPanel.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-2/xml/System.Windows.Forms/TableLayoutPanel.xml)
 - **Line 0, Column 0**: **[Error-ECMA2Yaml_InternalError]** 
`````
Intenal Several Error: System.Xml.XmlException: The 'summary' start tag on line 322 position 10 does not match the end tag of 'Docs'. Line 342, position 9.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at ECMA2Yaml.ECMALoader.LoadType(FileItem typeFile)
   at ECMA2Yaml.ECMALoader.LoadTypes(String basePath, Namespace ns)
`````

<a id="738cbe89"></a>
###
 - **Line 0, Column 0**: **[Error-ECMA2Yaml_File_LoadFailed]** `````Failed to load 1 files, aborting...`````
 - **Line 0, Column 0**: **[Error-file-not-found]** `````Invalid file link: '.sourcemap-ecma-0.json'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C7%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C202009070456246968-4814%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LGB6Ul381uwwvXuAhk62b9Z%2BsYM6SI%2F1lu5rhSMcCY4%3D&st=2020-09-07T04%3A53%3A33Z&se=2020-10-08T04%3A58%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-07 06:36 UTC, opbld30 commented
Docs Build status updates of commit _[7c2d3df](https://github.com/dotnet/dotnet-api-docs/commits/7c2d3df00cd40de31df8ad49076bc7cd8fa1027c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Windows.Forms/TableLayoutPanel.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-2/xml/System.Windows.Forms/TableLayoutPanel.xml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tablelayoutpanel?view=net-5.0&branch=pr-en-us-4814) | [Details](#user-content-56b81b83-f439df00)

<a id="56b81b83-f439df00"></a>
### [xml/System.Windows.Forms/TableLayoutPanel.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-2/xml/System.Windows.Forms/TableLayoutPanel.xml)
 - **Line 0, Column 0**: **[Warning-xref-not-found]** `````Cross reference not found: 'int.MaxValue*'.`````
 - **Line 0, Column 0**: **[Warning-xref-not-found]** `````Cross reference not found: 'int.MaxValue*'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C7%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C202009070619014258-4814%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FgjKzWmHS8K3ZAawaAPGaXDo1iqfSUEP0QIp%2BIrVs3c%3D&st=2020-09-07T06%3A31%3A50Z&se=2020-10-08T06%3A36%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-07 07:05 UTC, opbld34 commented
Docs Build status updates of commit _[2ba0d89](https://github.com/dotnet/dotnet-api-docs/commits/2ba0d892e8c15dceb29b5c2eb9fc95a5c2ca320e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Windows.Forms/TableLayoutPanel.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-2/xml/System.Windows.Forms/TableLayoutPanel.xml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tablelayoutpanel?view=net-5.0&branch=pr-en-us-4814) | [Details](#user-content-56b81b83-6452e4ce)

<a id="56b81b83-6452e4ce"></a>
### [xml/System.Windows.Forms/TableLayoutPanel.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-2/xml/System.Windows.Forms/TableLayoutPanel.xml)
 - **Line 0, Column 0**: **[Warning-xref-not-found]** `````Cross reference not found: 'Int32.MaxValue*'.`````
 - **Line 0, Column 0**: **[Warning-xref-not-found]** `````Cross reference not found: 'Int32.MaxValue*'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C7%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C202009070649333381-4814%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EzSrnX9F96zbROZy1vLoAqTMQy2JOvzkN6NZ%2BF7h5Ao%3D&st=2020-09-07T07%3A00%3A27Z&se=2020-10-08T07%3A05%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-09 18:51 UTC, carlossanlop commented
@merriemcgaw @JuditRose can you please review?

2020-09-09 18:54 UTC, merriemcgaw approved these changes

2020-09-09 19:50 UTC, gewarren requested changes

2020-09-09 19:50 UTC, gewarren commented on xml/System.Windows.Forms/TableLayoutPanel.xml
> + Setting the <xref:System.Windows.Forms.TableLayoutPanel.ColumnCount%2A> property does not create columns or allocate any backing memory. This allocation occurs when the columns are created, thus thi
```suggestion
 Setting the <xref:System.Windows.Forms.TableLayoutPanel.ColumnCount%2A> property does not create columns or allocate any backing memory. Memory allocation occurs when the columns are created, so you can set this property to <xref:System.Int32.MaxValue>.
```

2020-09-09 19:50 UTC, gewarren commented on xml/System.Windows.Forms/TableLayoutPanel.xml
> + Setting the <xref:System.Windows.Forms.TableLayoutPanel.RowCount%2A> property does not create rows or allocate any backing memory. This allocation occurs when the rows are created, thus this propert
```suggestion
 Setting the <xref:System.Windows.Forms.TableLayoutPanel.RowCount%2A> property does not create rows or allocate any backing memory. Memory allocation occurs when the rows are created, so you can set this property to <xref:System.Int32.MaxValue>.
```

2020-09-11 18:01 UTC, opbld33 commented
Docs Build status updates of commit _[a88711d](https://github.com/dotnet/dotnet-api-docs/commits/a88711dff4553ab0368c344a86e6b8b696224130)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Windows.Forms/TableLayoutPanel.xml](https://github.com/dotnet/dotnet-api-docs/blob/RussKie-patch-2/xml/System.Windows.Forms/TableLayoutPanel.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tablelayoutpanel?view=net-5.0&branch=pr-en-us-4814) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C11%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C202009111741147402-4814%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uMWuwkAYNDqGq1Sy9vcpjpgNgPXJf%2BZBnmz3dHvcGjk%3D&st=2020-09-11T17%3A56%3A31Z&se=2020-10-12T18%3A01%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-11 22:22 UTC, carlossanlop approved these changes

2020-09-11 22:26 UTC, gewarren approved these changes

2020-09-11 22:26 UTC, merged