Replace MSDN links
dotnet/dotnet-api-docs pull request #5242
Opened 2021-01-15 22:10 UTC by gewarren

2021-01-15 22:10 UTC, opbld32 commented
Docs Build status updates of commit _[fce812f](https://github.com/dotnet/dotnet-api-docs/commits/fce812f9cbd234b096a6c33b92ac11dedd308786)_: 

:clock10: **Pending**: waiting for processors ([36](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 36 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-15 22:30 UTC, opbld33 commented
Docs Build status updates of commit _[fce812f](https://github.com/dotnet/dotnet-api-docs/commits/fce812f9cbd234b096a6c33b92ac11dedd308786)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/Microsoft.Build.Tasks/CallTarget.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/CallTarget.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.calltarget?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.Build.Tasks/MSBuild.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/MSBuild.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.msbuild?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.Build.Tasks/ResolveComReference.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/ResolveComReference.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.resolvecomreference?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.JScript/ErrorType.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.JScript/ErrorType.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.jscript.errortype?view=netframework-1.1&branch=pr-en-us-5242) |
[xml/Microsoft.JScript/EvalErrorObject.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.JScript/EvalErrorObject.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.jscript.evalerrorobject?view=netframework-1.1&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.ApplicationServices/ApplicationBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.ApplicationServices/ApplicationBase.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.applicationservices.applicationbase?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.ApplicationServices/WindowsFormsApplicationBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.ApplicationServices/WindowsFormsApplicationBase.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.applicationservices.windowsformsapplicationbase?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.MyServices/ClipboardProxy.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.MyServices/ClipboardProxy.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.myservices.clipboardproxy?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/Collection.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/Collection.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.collection?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/ErrObject.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/ErrObject.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.errobject?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/Interaction.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/Interaction.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualC.StlClr/GenericPair`2.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualC.StlClr/GenericPair%602.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualc.stlclr.genericpair-2?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/Microsoft.Win32/FileDialog.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Win32/FileDialog.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.win32.filedialog?view=net-5.0&branch=pr-en-us-5242) |
[xml/System.Activities.Statements/CompensableActivity.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.Activities.Statements/CompensableActivity.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.activities.statements.compensableactivity?view=netframework-4.0&branch=pr-en-us-5242) |
[xml/System.Activities.Statements/CompensationToken.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.Activities.Statements/CompensationToken.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.activities.statements.compensationtoken?view=netframework-4.0&branch=pr-en-us-5242) |
[xml/System.AddIn.Contract/IListContract`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Contract/IListContract%601.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.contract.ilistcontract-1?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInEnvironment.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInEnvironment.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinenvironment?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInProcess.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInProcess.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinprocess?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInSecurityLevel.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInSecurityLevel.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinsecuritylevel?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInSegmentDirectoryNotFoundException.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInSegmentDirectoryNotFoundException.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinsegmentdirectorynotfoundexception?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInStore.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInStore.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinstore?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInToken.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInToken.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addintoken?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Pipeline/AddInAdapterAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Pipeline/AddInAdapterAttribute.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.pipeline.addinadapterattribute?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Pipeline/AddInBaseAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Syste [...]

2021-01-16 00:03 UTC, mairaw reviewed
I'm still going through this PR but leaving some comments for now

2021-01-16 00:03 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [pair (STL/CLR)](/previous-versions/bb385224(v=vs.140)).
better replacement?

```suggestion
 For more information, see [pair (STL/CLR)](/cpp/dotnet/utility-stl-clr#pair).  
```

2021-01-16 00:03 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [pair::pair (STL/CLR)](/previous-versions/bb385084(v=vs.140)).
```suggestion
 For more information, see [pair::pair (STL/CLR)](/cpp/dotnet/utility-stl-clr#pair_pair).  
```

2021-01-16 00:03 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [pair::pair (STL/CLR)](/previous-versions/bb385084(v=vs.140)).
```suggestion
 For more information, see [pair::pair (STL/CLR)](/cpp/dotnet/utility-stl-clr#pair_pair).  
```

2021-01-16 00:03 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [pair::pair (STL/CLR)](/previous-versions/bb385084(v=vs.140)).
```suggestion
 For more information, see [pair::pair (STL/CLR)](/cpp/dotnet/utility-stl-clr#pair_pair).  
```

2021-01-16 00:03 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [pair::pair (STL/CLR)](/previous-versions/bb385084(v=vs.140)).
```suggestion
 For more information, see [pair::pair (STL/CLR)](/cpp/dotnet/utility-stl-clr#pair_pair).  
```

2021-01-16 02:31 UTC, mairaw reviewed
A few more comments

2021-01-16 02:31 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [pair::pair (STL/CLR)](/previous-versions/bb385084(v=vs.140)).
```suggestion
 For more information, see [pair::pair (STL/CLR)](/cpp/dotnet/utility-stl-clr#pair_pair).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [operator== (pair) (STL/CLR)](/previous-versions/bb385174(v=vs.140)).
```suggestion
 For more information, see [operator== (pair) (STL/CLR)](/cpp/dotnet/utility-stl-clr#op_eq).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [pair::first (STL/CLR)](/previous-versions/bb385041(v=vs.140)).
```suggestion
 For more information, see [pair::first (STL/CLR)](/cpp/dotnet/utility-stl-clr#first).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/Microsoft.VisualC.StlClr/GenericPair`2.xml
> + For more information, see [pair::second (STL/CLR)](/previous-versions/bb386252(v=vs.140)).
```suggestion
 For more information, see [pair::second (STL/CLR)](/cpp/dotnet/utility-stl-clr#second).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/Microsoft.Win32/FileDialog.xml
> + See [Safe File Upload from an XBAP Sample](/previous-versions/aa358504(v=vs.100)).
```suggestion
 See [Safe File Upload from an XBAP Sample](/previous-versions/dotnet/netframework-3.5/aa358504(v=vs.90)).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Hosting/AddInProcess.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
Article doesn't sync to the TOC when URL is encoded

```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Hosting/AddInSecurityLevel.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Hosting/AddInStore.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Hosting/AddInToken.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Hosting/AddInToken.xml
> +        <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
        <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Hosting/AddInToken.xml
> +        <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
        <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Pipeline/AddInAdapterAttribute.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Pipeline/AddInBaseAttribute.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Pipeline/AddInContractAttribute.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Pipeline/CollectionAdapters.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Pipeline/ContractBase.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Pipeline/HostAdapterAttribute.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn/AddInAttribute.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/ns-System.AddIn.Contract.Automation.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.AddIn.Hosting/AddInEnvironment.xml
> +    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v%253dvs.100)">Add-Ins and Extensibility</related>
```suggestion
    <related type="Article" href="/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100)">Add-Ins and Extensibility</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.Collections.Generic/List`1.xml
> +    <related type="Article" href="/previous-versions/dscyy5s0(v=vs.140)">Iterators (C# and Visual Basic)</related>
```suggestion
    <related type="Article" href="/dotnet/csharp/programming-guide/concepts/iterators">Iterators (C#)</related>
    <related type="Article" href="/dotnet/visual-basic/programming-guide/concepts/iterators">Iterators (Visual Basic)</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.Collections.Generic/Stack`1.xml
> +    <related type="Article" href="/previous-versions/dscyy5s0(v=vs.140)">Iterators (C# and Visual Basic)</related>
```suggestion
    <related type="Article" href="/dotnet/csharp/programming-guide/concepts/iterators">Iterators (C#)</related>
    <related type="Article" href="/dotnet/visual-basic/programming-guide/concepts/iterators">Iterators (Visual Basic)</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.Collections/IEnumerable.xml
> +    <related type="Article" href="/previous-versions/dscyy5s0(v=vs.140)">Iterators (C# and Visual Basic)</related>
```suggestion
    <related type="Article" href="/dotnet/csharp/programming-guide/concepts/iterators">Iterators (C#)</related>
    <related type="Article" href="/dotnet/visual-basic/programming-guide/concepts/iterators">Iterators (Visual Basic)</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.Collections/IEnumerable.xml
> +        <related type="Article" href="/previous-versions/dscyy5s0(v=vs.140)">Iterators (C# and Visual Basic)</related>
```suggestion
        <related type="Article" href="/dotnet/csharp/programming-guide/concepts/iterators">Iterators (C#)</related>
        <related type="Article" href="/dotnet/visual-basic/programming-guide/concepts/iterators">Iterators (Visual Basic)</related>

```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/DataType.xml
> +-   A Dynamic Data Web site. This enables you to create a data context for the database and the class that contains the data field to customize and the methods to override. In addition, it creates th
```suggestion
-   A Dynamic Data Web site. This enables you to create a data context for the database and the class that contains the data field to customize and the methods to override. In addition, it creates the environment in which to use the page described before. For more information, see [Walkthrough: Creating a New Dynamic Data Web Site Using Scaffolding](/previous-versions/aspnet/cc488469(v=vs.100)).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/DataTypeAttribute.xml
> +    <related type="Article" href="/previous-versions/cc668199(v=vs.140)">How to: Customize Data Field Appearance and Behavior For Non-Intrinsic Data Types in the Data Model</related>
```suggestion
    <related type="Article" href="/previous-versions/aspnet/cc668199(v=vs.100)">How to: Customize Data Field Appearance and Behavior For Non-Intrinsic Data Types in the Data Model</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/ScaffoldColumnAttribute.xml
> +-   A Dynamic Data Web site. This enables you to create a data context for the database and the class that contains the data field to customize and the methods to override. In addition, it creates th
```suggestion
-   A Dynamic Data Web site. This enables you to create a data context for the database and the class that contains the data field to customize and the methods to override. In addition, it creates the environment in which to use the page described before. For more information, see [Walkthrough: Creating a New Dynamic Data Web Site Using Scaffolding](/previous-versions/aspnet/cc488469(v=vs.100)).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/ScaffoldTableAttribute.xml
> +-   A Dynamic Data Web site. This enables you to create a data context for the database and the class that contains the data field to customize and the methods to override. In addition, it creates th
```suggestion
-   A Dynamic Data Web site. This enables you to create a data context for the database and the class that contains the data field to customize and the methods to override. In addition, it creates the environment in which to use the page described before. For more information, see [Walkthrough: Creating a New Dynamic Data Web Site Using Scaffolding](/previous-versions/aspnet/cc488469(v=vs.100)).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/ScaffoldTableAttribute.xml
> +    <related type="Article" href="/previous-versions/cc488469(v=vs.140)">Walkthrough: Creating a New Dynamic Data Web Site using Scaffolding</related>
```suggestion
    <related type="Article" href="/previous-versions/aspnet/cc488469(v=vs.100)">Walkthrough: Creating a New Dynamic Data Web Site using Scaffolding</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/UIHintAttribute.xml
> +        <related type="Article" href="/previous-versions/cc488469(v=vs.140)">Walkthrough: Creating a New Dynamic Data Web Site using Scaffolding</related>
```suggestion
        <related type="Article" href="/previous-versions/aspnet/cc488469(v=vs.100)">Walkthrough: Creating a New Dynamic Data Web Site using Scaffolding</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/UIHintAttribute.xml
> + For a complete example, see [How to: Customize Data Field Display in the Data Model](/previous-versions/cc488522(v=vs.140)).
```suggestion
 For a complete example, see [How to: Customize Data Field Display in the Data Model](/previous-versions/aspnet/cc488522(v=vs.100)).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/UIHintAttribute.xml
> +    <related type="Article" href="/previous-versions/cc488522(v=vs.140)">How to: Customize Data Field Display in the Data Model</related>
```suggestion
    <related type="Article" href="/previous-versions/aspnet/cc488522(v=vs.100)">How to: Customize Data Field Display in the Data Model</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.DataAnnotations/ValidationException.xml
> + For more information about how to use this constructor, see [How to: Customize Data Field Validation in the Data Model](/previous-versions/cc488527(v=vs.140)).
```suggestion
 For more information about how to use this constructor, see [How to: Customize Data Field Validation in the Data Model](/previous-versions/aspnet/cc488527(v=vs.100)).  
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.Design.Serialization/DesignerSerializerAttribute.xml
> +    <related type="Article" href="/previous-versions/ms171834(v=vs.140)">Designer Serialization Overview</related>
```suggestion
    <related type="Article" href="/previous-versions/visualstudio/visual-studio-2012/ms171834(v=vs.110)">Designer Serialization Overview</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.Design.Serialization/DesignerSerializerAttribute.xml
> +        <related type="Article" href="/previous-versions/ms171834(v=vs.140)">Designer Serialization Overview</related>
```suggestion
        <related type="Article" href="/previous-versions/visualstudio/visual-studio-2012/ms171834(v=vs.110)">Designer Serialization Overview</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.Design.Serialization/DesignerSerializerAttribute.xml
> +        <related type="Article" href="/previous-versions/ms171834(v=vs.140)">Designer Serialization Overview</related>
```suggestion
        <related type="Article" href="/previous-versions/visualstudio/visual-studio-2012/ms171834(v=vs.110)">Designer Serialization Overview</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.Design.Serialization/DesignerSerializerAttribute.xml
> +        <related type="Article" href="/previous-versions/ms171834(v=vs.140)">Designer Serialization Overview</related>
```suggestion
        <related type="Article" href="/previous-versions/visualstudio/visual-studio-2012/ms171834(v=vs.110)">Designer Serialization Overview</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.Design.Serialization/DesignerSerializerAttribute.xml
> +        <related type="Article" href="/previous-versions/ms171834(v=vs.140)">Designer Serialization Overview</related>
```suggestion
        <related type="Article" href="/previous-versions/visualstudio/visual-studio-2012/ms171834(v=vs.110)">Designer Serialization Overview</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.Design.Serialization/DesignerSerializerAttribute.xml
> +        <related type="Article" href="/previous-versions/ms171834(v=vs.140)">Designer Serialization Overview</related>
```suggestion
        <related type="Article" href="/previous-versions/visualstudio/visual-studio-2012/ms171834(v=vs.110)">Designer Serialization Overview</related>
```

2021-01-16 02:31 UTC, mairaw commented on xml/System.ComponentModel.Design.Serialization/DesignerSerializerAttribute.xml
> +        <related type="Article" href="/previous-versions/ms171834(v=vs.140)">Designer Serialization Overview</related>
```suggestion
        <related type="Article" href="/previous-versions/visualstudio/visual-studio-2012/ms171834(v=vs.110)">Designer Serialization Overview</related>
```

2021-01-16 03:00 UTC, mairaw reviewed
A few more...

2021-01-16 03:00 UTC, mairaw commented on xml/ns-System.Web.UI.HtmlControls.xml
> +    <related type="Article" href="/previous-versions/t5d54cf8(v=vs.140)">HTML Controls for ASP.NET Web Pages</related>
```suggestion
    <related type="Article" href="/previous-versions/aspnet/t5d54cf8(v=vs.100)">HTML Controls for ASP.NET Web Pages</related>
```

2021-01-16 03:00 UTC, mairaw commented on xml/ns-System.Web.UI.HtmlControls.xml
> +    <related type="Article" href="/previous-versions/x8k61whf(v=vs.140)">Standard Toolbox Controls</related>
```suggestion
    <related type="Article" href="/previous-versions/aspnet/x8k61whf(v=vs.100)">Standard Toolbox Controls</related>
```

2021-01-16 03:09 UTC, mairaw requested changes
Final comments...

2021-01-16 03:09 UTC, mairaw commented on xml/ns-System.Web.UI.WebControls.xml
> +    <related type="Article" href="/previous-versions/k26w4zzx(v=vs.140)">Working with ASP.NET Web Server Controls</related>
```suggestion
    <related type="Article" href="/previous-versions/aspnet/k26w4zzx(v=vs.100)">Working with ASP.NET Web Server Controls</related>
```

2021-01-16 03:09 UTC, mairaw commented on xml/ns-System.Web.UI.WebControls.xml
> +    <related type="Article" href="/previous-versions/c4hb2k3a(v=vs.140)">Navigation Toolbox Controls</related>
```suggestion
    <related type="Article" href="/previous-versions/aspnet/c4hb2k3a(v=vs.100)">Navigation Toolbox Controls</related>
```

2021-01-16 03:09 UTC, mairaw commented on xml/ns-System.Web.UI.WebControls.xml
> +    <related type="Article" href="/previous-versions/tz6e5ezc(v=vs.140)">Login Toolbox Controls</related>
```suggestion
    <related type="Article" href="/previous-versions/aspnet/tz6e5ezc(v=vs.100)">Login Toolbox Controls</related>
```

2021-01-19 20:12 UTC, gewarren commented
Thanks Maira for the very thorough review! I will look more closely next time I run the CI job.

2021-01-19 20:13 UTC, opbld31 commented
Docs Build status updates of commit _[08db904](https://github.com/dotnet/dotnet-api-docs/commits/08db904104d15917cb01354491ddddca169ea33b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/Microsoft.Build.Tasks/CallTarget.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/CallTarget.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.calltarget?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.Build.Tasks/MSBuild.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/MSBuild.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.msbuild?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.Build.Tasks/ResolveComReference.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/ResolveComReference.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.resolvecomreference?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.JScript/ErrorType.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.JScript/ErrorType.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.jscript.errortype?view=netframework-1.1&branch=pr-en-us-5242) |
[xml/Microsoft.JScript/EvalErrorObject.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.JScript/EvalErrorObject.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.jscript.evalerrorobject?view=netframework-1.1&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.ApplicationServices/ApplicationBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.ApplicationServices/ApplicationBase.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.applicationservices.applicationbase?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.ApplicationServices/WindowsFormsApplicationBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.ApplicationServices/WindowsFormsApplicationBase.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.applicationservices.windowsformsapplicationbase?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.MyServices/ClipboardProxy.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.MyServices/ClipboardProxy.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.myservices.clipboardproxy?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/Collection.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/Collection.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.collection?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/ErrObject.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/ErrObject.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.errobject?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/Interaction.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/Interaction.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualC.StlClr/GenericPair`2.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualC.StlClr/GenericPair%602.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualc.stlclr.genericpair-2?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/Microsoft.Win32/FileDialog.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Win32/FileDialog.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.win32.filedialog?view=net-5.0&branch=pr-en-us-5242) |
[xml/System.Activities.Statements/CompensableActivity.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.Activities.Statements/CompensableActivity.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.activities.statements.compensableactivity?view=netframework-4.0&branch=pr-en-us-5242) |
[xml/System.Activities.Statements/CompensationToken.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.Activities.Statements/CompensationToken.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.activities.statements.compensationtoken?view=netframework-4.0&branch=pr-en-us-5242) |
[xml/System.AddIn.Contract/IListContract`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Contract/IListContract%601.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.contract.ilistcontract-1?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInEnvironment.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInEnvironment.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinenvironment?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInProcess.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInProcess.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinprocess?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInSecurityLevel.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInSecurityLevel.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinsecuritylevel?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInSegmentDirectoryNotFoundException.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInSegmentDirectoryNotFoundException.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinsegmentdirectorynotfoundexception?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInStore.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInStore.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinstore?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInToken.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInToken.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addintoken?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Pipeline/AddInAdapterAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Pipeline/AddInAdapterAttribute.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.pipeline.addinadapterattribute?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Pipeline/AddInBaseAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Syste [...]

2021-01-19 20:34 UTC, opbld34 commented
Docs Build status updates of commit _[da69020](https://github.com/dotnet/dotnet-api-docs/commits/da690201c517434bb655a945846b49984e9ed28b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/Microsoft.Build.Tasks/CallTarget.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/CallTarget.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.calltarget?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.Build.Tasks/MSBuild.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/MSBuild.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.msbuild?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.Build.Tasks/ResolveComReference.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Build.Tasks/ResolveComReference.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.resolvecomreference?view=msbuild-15&branch=pr-en-us-5242) |
[xml/Microsoft.JScript/ErrorType.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.JScript/ErrorType.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.jscript.errortype?view=netframework-1.1&branch=pr-en-us-5242) |
[xml/Microsoft.JScript/EvalErrorObject.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.JScript/EvalErrorObject.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.jscript.evalerrorobject?view=netframework-1.1&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.ApplicationServices/ApplicationBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.ApplicationServices/ApplicationBase.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.applicationservices.applicationbase?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.ApplicationServices/WindowsFormsApplicationBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.ApplicationServices/WindowsFormsApplicationBase.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.applicationservices.windowsformsapplicationbase?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic.MyServices/ClipboardProxy.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic.MyServices/ClipboardProxy.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.myservices.clipboardproxy?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/Collection.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/Collection.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.collection?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/ErrObject.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/ErrObject.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.errobject?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualBasic/Interaction.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualBasic/Interaction.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction?view=net-5.0&branch=pr-en-us-5242) |
[xml/Microsoft.VisualC.StlClr/GenericPair`2.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.VisualC.StlClr/GenericPair%602.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualc.stlclr.genericpair-2?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/Microsoft.Win32/FileDialog.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Microsoft.Win32/FileDialog.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.win32.filedialog?view=net-5.0&branch=pr-en-us-5242) |
[xml/System.Activities.Statements/CompensableActivity.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.Activities.Statements/CompensableActivity.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.activities.statements.compensableactivity?view=netframework-4.0&branch=pr-en-us-5242) |
[xml/System.Activities.Statements/CompensationToken.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.Activities.Statements/CompensationToken.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.activities.statements.compensationtoken?view=netframework-4.0&branch=pr-en-us-5242) |
[xml/System.AddIn.Contract/IListContract`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Contract/IListContract%601.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.contract.ilistcontract-1?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInEnvironment.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInEnvironment.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinenvironment?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInProcess.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInProcess.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinprocess?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInSecurityLevel.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInSecurityLevel.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinsecuritylevel?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInSegmentDirectoryNotFoundException.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInSegmentDirectoryNotFoundException.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinsegmentdirectorynotfoundexception?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInStore.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInStore.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addinstore?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Hosting/AddInToken.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Hosting/AddInToken.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.hosting.addintoken?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Pipeline/AddInAdapterAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/System.AddIn.Pipeline/AddInAdapterAttribute.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.addin.pipeline.addinadapterattribute?view=netframework-3.5&branch=pr-en-us-5242) |
[xml/System.AddIn.Pipeline/AddInBaseAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/msdn-011321/xml/Syste [...]

2021-01-19 21:46 UTC, mairaw commented
No worries! That's why I left these options for later because they're a bit trickier 😉

2021-01-19 21:48 UTC, mairaw approved these changes

2021-01-19 21:49 UTC, gewarren commented
> No worries! That's why I left these options for later because they're a bit trickier 😉

The product team is hoping to move the source of truth to the dotnet/runtime repo in the .NET 6 timeframe. So I wanted to run the CI tool while we still had it available. I will do a smaller chunk next time.

2021-01-19 21:50 UTC, merged