8 bytes minimum length validation has been removed
dotnet/dotnet-api-docs pull request #8280
Opened 2022-08-04 13:00 UTC by norcino

As raised in GitHub here:
https://github.com/dotnet/runtime/issues/61833

And decided here:
https://github.com/dotnet/runtime/issues/56908
https://github.com/dotnet/runtime/pull/57006

As per the current implementation:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/Rfc2898DeriveBytes.cs

The ArgumentException is not thrown anymore as the validation on the minimum length of the salt is not verified anymore.

Commit with the changes:
https://github.com/dotnet/runtime/commit/2ecec9caceb6378f94f8e0509b65de08e5fd041e#diff-08325fdc91c756ac12cd9ac088a682a266578fe47620cb8b4604d6883370405f

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2022-08-04 13:00 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=8280) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=8280) before we can accept your contribution.<br/><br/>:x: norcino [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=8280)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-api-docs?pullRequest=8280) it.</sub>

2022-08-04 13:25 UTC, opbld31 commented
Docs Build status updates of commit _[4a1232d](https://github.com/norcino/dotnet-api-docs/commits/4a1232d18575576c8895e9241465b1576cf6d773)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml](https://github.com/norcino/dotnet-api-docs/blob/patch-1/xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes?view=net-7.0&branch=pr-en-us-8280) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/500c749d-de78-3d4a-00e4-269d599bf9ec/202208041300130806-8280/BuildReport?accessString=058efef42dab72cbbf45e199e25c4c11f7cfdfe3ee7acb456382314d95978833).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 15:53 UTC, vcsjones commented
There was some discussion about changing this in https://github.com/dotnet/dotnet-api-docs/issues/6996.

I think some of the points that @bartonjs raises are worth considering. The limitation was removed for .NET 5+, but remains for .NET Framework and .NET Core. It's not immediately clear to me how to best convey that in the documentation.

2022-08-04 16:42 UTC, norcino commented
> There was some discussion about changing this in #6996.
> 
> I think some of the points that @bartonjs raises are worth considering. The limitation was removed for .NET 5+, but remains for .NET Framework and .NET Core. It's not immediately clear to me how to best convey that in the documentation.

Thank you for pointing it out, I won't get into the matter about whether or not the validation should be removed, but today I spent a few hours while I was upgrading a library from 3.1 to 6, because tests were expecting the failure which was not thrown.

I analyzed the document and found that in many tags they used already the attribute **FrameworkAlternate**, I will try to make the necessary changes and if the code will changed again, so we will with the documentation.

2022-08-04 16:43 UTC, norcino commented
> There was some discussion about changing this in #6996.
> 
> I think some of the points that @bartonjs raises are worth considering. The limitation was removed for .NET 5+, but remains for .NET Framework and .NET Core. It's not immediately clear to me how to best convey that in the documentation.

Thank you for pointing it out, I won't get into the matter about whether or not the validation should be removed, but today I spent a few hours while I was upgrading a library from 3.1 to 6, because tests were expecting the failure which was not thrown.

I analyzed the document and found that in many tags they used already the attribute **FrameworkAlternate**, I will make the changes.

2022-08-04 18:00 UTC, opbld31 commented
Docs Build status updates of commit _[13107c9](https://github.com/norcino/dotnet-api-docs/commits/13107c9ff32c4f6d6617d78aaabf946fb262e695)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml](https://github.com/norcino/dotnet-api-docs/blob/patch-1/xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes?view=net-7.0&branch=pr-en-us-8280) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/500c749d-de78-3d4a-00e4-269d599bf9ec/202208041731593944-8280/BuildReport?accessString=356134206cbd63c3e7ee3d8656d54202eea1c4d80af0347e1a11f4ed14173bc0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 22:02 UTC, gewarren requested changes

2022-08-04 22:02 UTC, gewarren commented on xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml
> + The salt size should be 8 bytes or larger and the iteration count must be greater than zero. The minimum recommended number of iterations is 1000.
```suggestion
In .NET Framework and .NET Core 1.0 - 3.1, the salt size must be 8 bytes or larger. In all versions, the iteration count must be greater than zero. The minimum recommended number of iterations is 1000.  
```

2022-08-04 22:02 UTC, gewarren commented on xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml
> +        <remarks FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;net
Can only be one remarks section.

2022-08-04 22:02 UTC, gewarren commented on xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml
> + The salt size should be 8 bytes or larger and the iteration count must be greater than zero. The minimum recommended number of iterations is 1000.
```suggestion
In .NET Framework and .NET Core 1.0 - 3.1, the salt size must be 8 bytes or larger. In all versions, the iteration count must be greater than zero. The minimum recommended number of iterations is 1000.  
```

2022-08-04 22:02 UTC, gewarren commented on xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml
> +        <remarks FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;net
There can only be one remarks section.

2022-08-04 22:02 UTC, gewarren commented on xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml
> +        <remarks FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;net
Duplicate remarks section.

2022-08-04 22:02 UTC, gewarren commented on xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml
> + The salt size should be 8 bytes or larger and the iteration count must be greater than zero. The minimum recommended number of iterations is 1000.
```suggestion
In .NET Framework and .NET Core 1.0 - 3.1, the salt size must be 8 bytes or larger. In all versions, the iteration count must be greater than zero. The minimum recommended number of iterations is 1000.
```

2023-08-24 16:28 UTC, Jozkee commented
Will close this PR for now since it has been stale for one year.

2023-08-24 16:28 UTC, closed without merging