GetFullPath does not throw NotSupportedException in netcore
dotnet/dotnet-api-docs pull request #8387
Opened 2022-09-14 19:21 UTC by plade

## Summary

GetFullPath does not throw NotSupportedException for invalid paths since Net Core 2.1.
More details are in [this blog post](https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek) and in the issue discussion.

Fixes #33477

2022-09-14 19:39 UTC, gewarren commented
Related breaking change doc: https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.1#path-apis-dont-throw-an-exception-for-invalid-characters. Does that need to be updated too @carlossanlop?

2022-09-14 19:46 UTC, gewarren requested changes
We do need to leave the exception there for .NET Framework, so instead of removing it, just prefix it with: ".NET Framework only: ...". Or if we still need to mention the .NET Core versions, ".NET Framework and .NET Core 1.0 - 2.0 only: ...".

2022-09-14 19:48 UTC, opbld33 commented
Docs Build status updates of commit _[999f625](https://github.com/plade/dotnet-api-docs/commits/999f625e8cf1a8ab21bfd24514ffc6389ab0ccff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.IO/Path.xml](https://github.com/plade/dotnet-api-docs/blob/plade-patch-1/xml/System.IO/Path.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.io.path?view=net-7.0&branch=pr-en-us-8387) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/500c749d-de78-3d4a-00e4-269d599bf9ec/202209141922001759-8387/BuildReport?accessString=e5ad5e8cc612ef4334bfce5596e9a5595edb512daddea23a5cc8c1279628b16c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-12 01:15 UTC, closed without merging

2022-10-12 01:16 UTC, plade commented
I'm not sure what the intended behavior is like. Closing so that someone else can take over.