Fix operator docs
dotnet/dotnet-api-docs pull request #8692
Opened 2022-12-06 18:27 UTC by jairosoto05

Reverse operator docs and change the word implicitly to explicitly Fixes #8318

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2022-12-06 18:27 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=8692) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=8692) before we can accept your contribution.<br/><br/>:x: jairosoto05 [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=8692)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-api-docs?pullRequest=8692) it.</sub>

2022-12-06 18:31 UTC, opbld34 commented
Learn Build status updates of commit _[d21aa67](https://github.com/jairosoto05/dotnet-api-docs/commits/d21aa67d8dce53cbb81f66e946c2e905a3379bb0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c5bd136d)
[xml/System.Text.Json.Nodes/JsonNode.xml](https://github.com/jairosoto05/dotnet-api-docs/blob/jairosoto05-patch-1/xml/System.Text.Json.Nodes/JsonNode.xml) | :x:Error | | [Details](#user-content-fa756ecc8cd83a118f0d86fcd7e9fe30-c5bd136d)

<a id="c5bd136d"></a>
###
 - **Line 0, Column 0**: **[Error: ECMA2Yaml_File_LoadFailed]** `````Failed to load 1 files, aborting...`````

<a id="fa756ecc8cd83a118f0d86fcd7e9fe30-c5bd136d"></a>
### [xml/System.Text.Json.Nodes/JsonNode.xml](https://github.com/jairosoto05/dotnet-api-docs/blob/jairosoto05-patch-1/xml/System.Text.Json.Nodes/JsonNode.xml)
 - **Line 0, Column 0**: **[Error: ECMA2Yaml_InternalError]** 
`````
Intenal Several Error: System.Xml.XmlException: Name cannot begin with the '.' character, hexadecimal value 0x2E. Line 551, position 142.
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at ECMA2Yaml.ECMALoader.LoadType(FileItem typeFile)
   at ECMA2Yaml.ECMALoader.LoadTypes(String basePath, Namespace ns)
`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/500c749d-de78-3d4a-00e4-269d599bf9ec/202212061827252455-8692/BuildReport?accessString=18b6cd831c5f6308e9bb5ddff9e4d92652b3394136c70e6539b02bf673ceaafe).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 18:44 UTC, gewarren requested changes

2022-12-06 18:44 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <param name="value">A <see cref="T:System.Boolean" /> to explicitly convert.</param>
From here on down, these are implicit operators.

2022-12-06 18:44 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <summary>Defines an implicit conversion of a given <see cref="T:System.Text.Json.Nodes.JsonNode" /> to a <see cref="T:System.Boolean" />.</summary>
This was correct as originally written.

2022-12-06 18:44 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <summary>Defines an implicit conversion of a given <see cref="T:System.Text.Json.Nodes.JsonNode" /> to a <see cref="T:System.Boolean" />.</summary>
I think all the changes to the implicit operators should be reverted.

2022-12-06 18:45 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <summary>Defines an explicit conversion of a given see cref="T:System.Text.Json.Nodes.JsonNode" /> to a <see cref="T:System.Byte" /><.</summary>
```suggestion
        <summary>Defines an explicit conversion of a given <see cref="T:System.Text.Json.Nodes.JsonNode" /> to a <see cref="T:System.Byte" />.</summary>
```

2022-12-06 19:24 UTC, opbld31 commented
Learn Build status updates of commit _[fbf2ea8](https://github.com/jairosoto05/dotnet-api-docs/commits/fbf2ea87e295cc971c0bbcb09b745b3c2ac92335)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Text.Json.Nodes/JsonNode.xml](https://github.com/jairosoto05/dotnet-api-docs/blob/jairosoto05-patch-1/xml/System.Text.Json.Nodes/JsonNode.xml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonnode?view=net-7.0&branch=pr-en-us-8692) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/500c749d-de78-3d4a-00e4-269d599bf9ec/202212061853463377-8692/BuildReport?accessString=ff8f76011ecb151682c344d38e2ecfab2824772e5ef8dcb06f2c7716b4e14928).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 21:24 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <param name="value">A <see cref="T:System.Boolean" /> to explicitly convert.</param>
```suggestion
        <param name="value">A <see cref="T:System.Text.Json.Nodes.JsonNode" /> to explicitly convert.</param>
```

2022-12-06 21:24 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <param name="value">A <see cref="T:System.Boolean" /> to explicitly convert.</param>
And similarly for others...

2022-12-06 21:24 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <summary>Defines an implicit conversion of a given <see cref="T:System.Text.Json.Nodes.JsonNode" /> to a <see cref="T:System.Boolean" />.</summary>
```suggestion
        <summary>Defines an implicit conversion of a given <see cref="T:System.Boolean" /> to a <see cref="T:System.Text.Json.Nodes.JsonNode" />.</summary>
```

2022-12-06 21:24 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <summary>Defines an implicit conversion of a given <see cref="T:System.Text.Json.Nodes.JsonNode" /> to a <see cref="T:System.Boolean" />.</summary>
And similarly for the other implicit operators.

2022-12-06 21:24 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <summary>Defines an implicit conversion of a given <see cref="T:System.Text.Json.Nodes.JsonNode" /> to a <see cref="T:System.Boolean" />.</summary>
```suggestion
        <summary>Defines an implicit conversion of a specified nullable <see cref="T:System.Boolean" /> to a nullable <see cref="T:System.Text.Json.Nodes.JsonNode" />.</summary>
```

2022-12-06 21:24 UTC, gewarren commented on xml/System.Text.Json.Nodes/JsonNode.xml
> +        <summary>Defines an explicit conversion of a given <see cref="T:System.Text.Json.Nodes.JsonNode" /> to a <see cref="T:System.Boolean" />.</summary>
```suggestion
        <summary>Defines an explicit conversion of a given nullable <see cref="T:System.Text.Json.Nodes.JsonNode" /> to a nullable <see cref="T:System.Boolean" />.</summary>
```

2022-12-06 22:42 UTC, opbld30 commented
Learn Build status updates of commit _[1bb665a](https://github.com/jairosoto05/dotnet-api-docs/commits/1bb665a6597b38edbd87fd7bbc477ee90beb516d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Text.Json.Nodes/JsonNode.xml](https://github.com/jairosoto05/dotnet-api-docs/blob/jairosoto05-patch-1/xml/System.Text.Json.Nodes/JsonNode.xml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonnode?view=net-7.0&branch=pr-en-us-8692) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/500c749d-de78-3d4a-00e4-269d599bf9ec/202212062215318272-8692/BuildReport?accessString=385581b92bbeeaf89c41ab8d847e9e7abf71ceb3b26fb339bb2c34d1514ea379).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 23:09 UTC, opbld30 commented
Learn Build status updates of commit _[6f26ae9](https://github.com/jairosoto05/dotnet-api-docs/commits/6f26ae952b27e5cd2a45a676e82ce4a4a24c6d37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Text.Json.Nodes/JsonNode.xml](https://github.com/jairosoto05/dotnet-api-docs/blob/jairosoto05-patch-1/xml/System.Text.Json.Nodes/JsonNode.xml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonnode?view=net-7.0&branch=pr-en-us-8692) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/500c749d-de78-3d4a-00e4-269d599bf9ec/202212062218472894-8692/BuildReport?accessString=baa8c3a224a1db45de74a6e341b70daaad0ca8369471a4bd071bfc9e5091050f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 01:32 UTC, opbld31 commented
Learn Build status updates of commit _[ded2f7d](https://github.com/jairosoto05/dotnet-api-docs/commits/ded2f7db66c1cd937d14e54960f664c1c8e37b9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Text.Json.Nodes/JsonNode.xml](https://github.com/jairosoto05/dotnet-api-docs/blob/jairosoto05-patch-1/xml/System.Text.Json.Nodes/JsonNode.xml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonnode?view=net-7.0&branch=pr-en-us-8692) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/500c749d-de78-3d4a-00e4-269d599bf9ec/202212070105041009-8692/BuildReport?accessString=d5d55d303f5d72d80d09fa0d31220b5afd3385f7a3bad921384866d9284fa7ba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 05:58 UTC, gewarren approved these changes

2023-01-25 16:19 UTC, merged