Modernize 3DES examples
dotnet/dotnet-api-docs pull request #8742
Opened 2022-12-27 12:49 UTC by svick

Related to https://github.com/dotnet/runtime/issues/79924.

This PR deletes some outdated and duplicate samples for 3DES, modernizes the C# version of the remaining sample and removes samples from the obsolete `TripleDESCryptoServiceProvider` class.

Also updates the remarks of `TripleDESCryptoServiceProvider` to link to the `TripleDES.Create` method.

2023-01-04 18:44 UTC, bartonjs commented
This was already fixed in https://github.com/dotnet/dotnet-api-docs/pull/8384.  Not sure why the updated samples aren't showing up on there; but that's the structure and style that I rewrote these samples to, and would prefer to not change any of the styling.

2023-01-04 18:55 UTC, vcsjones commented
@bartonjs I think your previous PR only addressed `TripleDES`. I don't see `TripleDESCryptoServiceProvider` in your linked PR.

2023-01-04 19:34 UTC, bartonjs commented
In that case.. the text updates and deleting all of the examples that pertain specifically to TripleDESCryptoServiceProvider are welcome; but changing the C# 3DES example is not (because then it doesn't match the VB or CPP-CLI samples, or the AES/RC2/etc samples).

2023-01-04 19:35 UTC, bartonjs commented on snippets/csharp/System.Security.Cryptography/TripleDES/Create/memoryexample.cs
> +    static async Task Main()
Please revert all changes in this file.

2023-01-04 19:36 UTC, bartonjs requested changes
The 3DES core C# samples should remain as-is, so they are consistent across languages and similar classes.

2023-01-15 13:04 UTC, svick commented
@bartonjs I think that having outdated C# examples is worse than being inconsistent.

I would be fine with updating examples for other classes or for the other languages (where possible), but I really think the primary examples should demonstrate modern coding styles.

2025-04-03 18:09 UTC, gewarren approved these changes
Let's just delete the C++ examples.

2025-04-03 18:09 UTC, gewarren commented on xml/System.Security.Cryptography/TripleDES.xml
> + :::code language="cpp" source="~/snippets/cpp/VS_Snippets_CLR/Cryptography.3DES.Create.File/CPP/fileexample.cpp" id="Snippet1":::
```suggestion
```

2025-04-03 18:09 UTC, gewarren commented on xml/System.Security.Cryptography/TripleDES.xml
> + :::code language="cpp" source="~/snippets/cpp/VS_Snippets_CLR/Cryptography.3DES.Create.Memory/CPP/memoryexample.cpp" id="Snippet1":::
```suggestion
```

2025-04-03 18:09 UTC, gewarren commented on xml/System.Security.Cryptography/TripleDES.xml
>   :::code language="cpp" source="~/snippets/cpp/VS_Snippets_CLR/Cryptography.3DES.Create.Memory/CPP/memoryexample.cpp" id="Snippet1":::
```suggestion
```

2025-04-03 19:32 UTC, gewarren approved these changes

2025-04-03 19:57 UTC, bartonjs approved these changes

2025-04-03 19:59 UTC, merged