DriveInfo.xml: improve for non-Windows platforms
dotnet/dotnet-api-docs pull request #8929
Opened 2023-03-27 21:51 UTC by alxu-avpt

2023-03-27 22:15 UTC, gewarren requested changes

2023-03-27 22:15 UTC, gewarren commented on xml/System.IO/DriveInfo.xml
>          <summary>Provides access to information on the specified drive.</summary>
```suggestion
        <summary>Creates a new instance of the <see cref="T:System.IO.DriveInfo" /> class.</summary>
```

2023-03-27 22:15 UTC, gewarren commented on xml/System.IO/DriveInfo.xml
> + Use this class to obtain information on drives. You cannot use this method to obtain information on drive names that are `null` or use UNC (\\\server\share) paths.
```suggestion
You can't use this constructor to obtain information on drive names that are <see langword="null" /> or use UNC (`\\server\share`) paths.  
```

2023-03-27 22:15 UTC, gewarren commented on xml/System.IO/DriveInfo.xml
> + On Windows, passing a mounted directory (e.g. C:\NetworkMountedDrive) returns the root drive information (e.g. C:).
The constructor doesn't technically return anything, so this should be reworded.

2023-05-12 08:41 UTC, adamsitnik reviewed
@alxu-avpt could you please address the feedback from @gewarren ?

2023-05-15 17:46 UTC, alxu-avpt commented
@dotnet-policy-service agree company="AvePoint"

2023-05-15 17:48 UTC, alxu-avpt commented
> @alxu-avpt could you please address the feedback from @gewarren ?

Sorry, I was applying for CLA approval from my company. Please re-review, thanks!

2023-05-15 18:07 UTC, gewarren approved these changes
Thanks @alxu-avpt

2023-05-15 18:21 UTC, gewarren commented on xml/System.IO/DriveInfo.xml
> + You can't use this constructor to obtain information on drive names that are <see langword="null" /> or use UNC (`\\server\share`) paths.
```suggestion
 You can't use this constructor to obtain information on drive names that are `null` or use UNC (`\\server\share`) paths.
```

2023-05-15 19:31 UTC, merged