Adjust remarks for Assembly.Load on .NET Core
dotnet/dotnet-api-docs pull request #9764
Opened 2024-03-26 04:49 UTC by agocke

## Summary

The existing docs are only valid for .NET Framework.

Fixes #38987

2024-03-26 12:40 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> +The assembly is loaded into the default AssemblyLoadContext.
This overload throws NotSupportedException in .NET Core 2.0+:

https://github.com/dotnet/runtime/blob/b432fc66fe59873b2b2ad584c04eaf1e4b11d611/src/libraries/System.Private.CoreLib/src/System/Reflection/Assembly.cs#L390

2024-03-26 12:43 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> +This API is present in .NET Core for compatibility, but it is recommended to use <xref:System.Reflection.AssemblyLoadContext> overloads in .NET Core 2.0 and later.
I am not sure about this recommendation for the Assembly.Load overloads that take AssemblyName or assembly name string. I do not think that these overloads are problematic and it is typically fine to use them even .NET Core 2.0+.

2024-03-26 12:55 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> +The assembly is loaded into the current AssemblyLoadContext.
Add a link to https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed#algorithm ?

2024-03-26 13:05 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> +This API is present in .NET Core for compatibility, but it is recommended to use <xref:System.Reflection.AssemblyLoadContext> overloads in .NET Core 2.0 and later.
My assumption is that the typical caller of these Assembly.Load overloads wants to load the assembly into its own context. The explicit replacement of `Assembly.Load(assemblyName)` is `AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly())!.LoadFromAssemblyName(assemblyName)` that is way more complicated.

2024-03-28 04:25 UTC, gewarren requested changes

2024-03-28 04:25 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
> +        <remarks FrameworkAlternate="netcore-2.0;netcore-2.1;netcore-2.2;netcore-3.0;net-5.0;net-6.0;net-7.0;net-8.0;net-9.0">
Remarks can't be versioned like this unfortunately. You just have to annotate them in the text itself where they are version specific.

2024-04-16 23:48 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> +In .NET Core 2.0 and later, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://lear
```suggestion
In .NET Core/5+, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed#algorithm" />.
```

2024-04-16 23:48 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> +In .NET Core 2.0 and later, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://lear
```suggestion
In .NET Core/5+, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed#algorithm" />.
```

2024-04-16 23:48 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> + In .NET Core 2.0 and later, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://lea
```suggestion
 In .NET Core/5+, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed#algorithm" />.
```

2024-04-16 23:48 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> + Before .NET 5, the following applied:
```suggestion
 In .NET Framework, the following applied:
```

2024-04-16 23:48 UTC, jkotas commented on xml/System.Reflection/Assembly.xml
> +
```suggestion
 This API is not supported in .NET Core/5+. It will always throw <xref:System.NotSupportedException>.

```

2024-09-03 21:51 UTC, gewarren approved these changes

2024-09-03 21:51 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
> +> **.NET Framework only:** See [`<loadFromRemoteSources>`](/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element) for loading assemblies from remote locations.
```suggestion
> **.NET Framework only:** For information about loading assemblies from remote locations, see [`<loadFromRemoteSources>`](/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element).
```

2024-09-03 21:51 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
>  >  File transfer protocol (FTP) is not supported. If the URI supplied for `assemblyFile` is an FTP address, the assembly is not loaded. No exception is thrown.
```suggestion
> .NET Framework only: File transfer protocol (FTP) is not supported. If the URI supplied for `assemblyFile` is an FTP address, the assembly is not loaded. No exception is thrown.
```

2024-09-03 21:51 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
> +
```suggestion
```

2024-09-03 21:51 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
> + The assembly is loaded into the default AssemblyLoadContext. For more information on assembly loading, see <see cref="https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed
```suggestion
The assembly is loaded into the default AssemblyLoadContext. For more information on assembly loading, see [Managed assembly loading algorithm](/dotnet/core/dependency-loading/loading-managed#algorithm").
```

2024-09-03 21:51 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
> + The assembly is loaded into a new AssemblyLoadContext created for this purpose. For more information on assembly loading, see <see cref="https://learn.microsoft.com/en-us/dotnet/core/dependency-load
```suggestion
The assembly is loaded into a new AssemblyLoadContext created for this purpose. For more information on assembly loading, see [Managed assembly loading algorithm](/dotnet/core/dependency-loading/loading-managed#algorithm").
```

2024-09-03 21:51 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
> + In .NET Core/5+, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://learn.microsof
```suggestion
In .NET Core/5+, the target assembly is loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see [Managed assembly loading algorithm](/dotnet/core/dependency-loading/loading-managed#algorithm").
```

2024-09-03 21:51 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
> +In .NET Core/5+, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://learn.microsoft
```suggestion
In .NET Core/5+, the target assembly is loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see [Managed assembly loading algorithm](/dotnet/core/dependency-loading/loading-managed#algorithm").
```

2024-09-03 21:51 UTC, gewarren commented on xml/System.Reflection/Assembly.xml
> +In .NET Core/.NET 5+, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see <see cref="https://learn.micr
```suggestion
In .NET Core/.NET 5+, the target assembly will be loaded into the current <xref:System.Runtime.Loader.AssemblyLoadContext>. For more information on assembly loading, see [Managed assembly loading algorithm](/dotnet/core/dependency-loading/loading-managed#algorithm").
```

2024-10-24 03:36 UTC, merged